config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  #match 'users_new', to: 'users#new', via: [:get], as: 'users_new_path'
  resources :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match 'signup', to: 'users#new', via: [:get], as: 'signup_path'
  match 'signin', to: 'sessions#new', via: [:get], as: 'signin_path'
  match 'signout', to: 'sessions#destroy', via: [:delete], as: 'signout_path'

  #get 'static_pages/home'
  #match 'home', to: 'static_pages#home', via: [:get], as: 'root_path'
  root to: 'static_pages#home', as: 'root_path'

  #get 'static_pages/help'
  match 'help', to: 'static_pages#help', via: [:get], as: 'help_path'
  #match 'help', to: 'static_pages#help', as: 'help_path'

  #get 'static_pages/about'
  match 'about', to: 'static_pages#about', via: [:get], as: 'about_path'

  #get 'static_pages/contact'
  match 'contact', to: 'static_pages#contact', via: [:get], as: 'contact_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>Sample App</h1>
<p>
  This is the about page for the <a href="http:/railstutorial.org/"> Ruby on Rails Tutorial</a>
  sample application
</p>

app/views/static_pages/contact.html.erb
<%provide (:title, 'Contact')%>

  <h1>contact</h1>
  <h3>
    Contact Ruby on Rails Tutorial about the sample app at the
    <a href="http:/railstutorial.org/"> contact page</a>

  </h3>
  <%=link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>
<%=link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'%>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed'%>
    </div>
  </div>
<%else%>
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the <a href="http:/railstutorial.org/"> Ruby on Rails Tutorial</a>
    sample application
  </h2>
  <%=link_to "Sign up now!", signup_path_url, class: "btn btn-large btn-primary" %>
</div>
<%=link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'%>
<%end%>