config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  #match 'users_new', to: 'users#new', via: [:get], as: 'users_new_path'
  resources :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match 'signup', to: 'users#new', via: [:get], as: 'signup_path'
  match 'signin', to: 'sessions#new', via: [:get], as: 'signin_path'
  match 'signout', to: 'sessions#destroy', via: [:delete], as: 'signout_path'

  #get 'static_pages/home'
  #match 'home', to: 'static_pages#home', via: [:get], as: 'root_path'
  root to: 'static_pages#home', as: 'root_path'

  #get 'static_pages/help'
  match 'help', to: 'static_pages#help', via: [:get], as: 'help_path'
  #match 'help', to: 'static_pages#help', as: 'help_path'

  #get 'static_pages/about'
  match 'about', to: 'static_pages#about', via: [:get], as: 'about_path'

  #get 'static_pages/contact'
  match 'contact', to: 'static_pages#contact', via: [:get], as: 'contact_path'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer"> <small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
<ul>
<li><%= link_to "About", about_path_url %></li>
<li><%= link_to "Contact", contact_path_url %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        <%= link_to "sample app", root_path_url, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path_url %></li>
              <li><%= link_to "Help", help_path_url %></li>
              <% if signed_in?%>
                  <li><%= link_to "Users", users_path %></li>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path_url, method: "delete"%>
                      </li>
                    </ul>
                  </li>
                <% else %>
                    <li><%= link_to "Sign in", signin_path_url %></li>
                <% end %>
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value|%>
        <div class="alert alert-<%= key %>"><%= value%></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>